import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Auth from "@/components/auth/Auth";
import NavBar from "@/components/navbar/NavBar";
import { isAuthenticated } from "@/utils/amplify-utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authBool = await isAuthenticated(); // authBool ahora es de tipo boolean
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Auth>
          <NavBar isSignedIn={authBool} /> {/* authBool ahora es de tipo boolean */}
          {children}
        </Auth>
      </body>
    </html>
  );
}